'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property Emp_ID As String
    Public Property Emp_Name As String
    Public Property Age As String
    Public Property PhoneNo As String
    Public Property Sex As String

End Class
